version: '2'

services:
  redis:
    image: docker.io/bitnami/redis:6.2
    env_file: ./env/redis.env
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
