version: '3'

services:
    mongodb:
        image: mongo:latest
        env_file: ./db/db.env
        ports:
            - 27017:27017
        volumes:
            - ./db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
            - mongodb-volume:/data/db
    bot:
        build:
            context: ./src
            dockerfile: ./BarcaBot/Dockerfile
        ports:
            - 5001:80
        depends_on:
            - mongodb
        deploy:
            restart_policy:
                condition: on-failure

volumes:
    mongodb-volume: