DiscordSettings:
  Prefix: "="
  Token: ""
DatabaseSettings:
  ConnectionString: ""
  DatabaseName: ""
ApisSettings:
  ApiFootball:
    Token: ""
    Season: "2020-2021"
  FootballData:
    Token: ""
  Plotly:
    Username: ""
    Token: ""