# Rename to appsettings.yml before building the bot
DiscordSettings:
  Prefix: ""
  Token: ""
DatabaseSettings:
  Server: ""
  Name: ""
  Username: ""
  Password: ""
ApisSettings:
  ApiFootball:
    Token: ""
    Season: ""
  FootballData:
    Token: ""